name: Prerelease Label Handler

on:
  issues:
    types:
      - labeled

jobs:
  comment_on_prerelease:
    if: github.event.label.name == 'prerelease'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - name: Gather participants
        id: participants
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.payload.issue.number;
            const repo = context.repo;

            // Get issue details (for author)
            const issue = context.payload.issue;
            const author = issue.user.login;

            // Get all comments
            const comments = await github.paginate(
              github.rest.issues.listComments,
              { ...repo, issue_number }
            );
            const commenters = new Set(comments.map(c => c.user.login));
            commenters.delete(author); // Don't double-mention author

            // Get all reactions
            const all_reactors = new Set();
            for (const comment of comments) {
              const reactions = await github.paginate(
                github.rest.reactions.listForIssueComment,
                { ...repo, comment_id: comment.id }
              );
              reactions.forEach(r => all_reactors.add(r.user.login));
            }
            // Reactions on main issue body
            const issue_reactions = await github.paginate(
              github.rest.reactions.listForIssue,
              { ...repo, issue_number }
            );
            issue_reactions.forEach(r => all_reactors.add(r.user.login));

            // Remove author/commenters from reactors to avoid duplicate mentions
            all_reactors.delete(author);
            commenters.forEach(u => all_reactors.delete(u));

            // Filter out bot users
            const isBotUser = (username) => {
              return username.endsWith('[bot]') || 
                username.includes('bot') || 
                ['dependabot', 'renovate', 'greenkeeper', 'codecov', 'coveralls'].includes(username.toLowerCase());
            };

            // Combine all usernames:
            const all_users = [author, ...commenters, ...all_reactors].filter(user => !isBotUser(user));

            if (all_users.length === 0) {
              return { mentions: "" };
            }

            const mentions = all_users.map(u => `@${u}`).join(' ');

            return { mentions };
          result-encoding: string

      - name: Add prerelease comment
        uses: actions/github-script@v7
        with:
          script: |
            const mentions = '${{steps.participants.outputs.mentions}}';

            if (mentions.trim() === "") {
              console.log("No participants to mention. Skipping comment creation.");
              return;
            }
            const message = `${mentions}\n\nA fix for this issue is now available in the next pre-releases of C#DK/C#. If you'd like to try out the fix, please see [these instructions](https://github.com/microsoft/vscode-dotnettools/wiki/Installing-and-updating-pre%E2%80%90release-versions-of-C%23-Dev-Kit-and-C%23-Extension) to update or try pre-release versions.`;

            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.payload.issue.number,
              body: message
            });
